const Vuex = require("vuex")
module.exports = new Vuex.Store({
  state: {
    entropy:null,
    confPayload:null,
    finishNextPage:null,
    easyUnit:false,
    fiat:"jpy",
    showLabelPayload:{},
    tsMode:"relative",
    detail:{},
    zaifPayEnabled:false,
    monappyEnabled:false,
    monapartyEnabled:false,
    sendUrl:"",
    zaifPayInvoiceId:"",
    hasKeyPairs:false,
    transparency:false,
    tokenInfo:"",
    coinId:"",
    addr:"",
    sendable:false,
    openSide:false,
    bgClass:"sand",
    monapartyTitle:"",
    divisible:false,
    includeUnconfirmedFunds:false,
    utxoStr:"",
    error:""
  },
  mutations: {
    setEntropy(state,ent) {
      state.entropy=ent;
    },
    openSide(state,v) {
      state.openSide=v;
    },
    deleteEntropy(state){
      state.entropy=null
    },
    setSettings(state,d){
      //d can be incomplete,please be careful
      state.zaifPayEnabled=d.zaifPay?d.zaifPay.enabled:false
      state.monappyEnabled=d.monappy?d.monappy.enabled:false
      state.monapartyEnabled=d.monaparty?d.monaparty.enabled:true
      state.fiat=d.fiat||"jpy"
      state.easyUnit=d.useEasyUnit
      state.tsMode=d.absoluteTime?"absolute":"relative"
      state.bgClass=d.monaparty&&d.monaparty.bgClass||"sand"
      state.monapartyTitle=d.monaparty&&d.monaparty.title||"monacard"
      state.includeUnconfirmedFunds=d.includeUnconfirmedFunds
    },
    setTitle(s,title){
      s.monapartyTitle=title||"monacard"
    },
    setConfirmation(state,payload){
      state.confPayload={
        address:payload.address,
        amount:parseFloat(payload.amount),
        fiat:parseFloat(payload.fiat),
        feePerByte:parseInt(payload.feePerByte,10),
        message:payload.message,
        coinType:payload.coinType,
        txLabel:payload.txLabel,
        utxoStr:payload.utxoStr
      }
    },
    setFinishNextPage(state,pageData){
      state.finishNextPage={
        page:pageData.page,
        infoId:pageData.infoId,
        payload:pageData.payload
      };
    },
    setEasyUnit(state,flag){
      state.easyUnit=!!flag
    },
    setLabelToShow(state,param){
      state.showLabelPayload={
        coinId:param.coinId,
        name:param.name,
        index:param.index,
        change:param.change
      }
    },
    setTxDetail(state,d){
      state.detail.coinId=d.coinId
      state.detail.txId=d.txId
    },
    setSendUrl(state,url){
      state.sendUrl=url||""
    },
    setZaifPayInvoiceId(state,id){
      state.zaifPayInvoiceId=id||""
    },
    setKeyPairsExistence(state,flag){
      state.hasKeyPairs=flag
    },
    setTransparency(state,flg) {
      state.transparency=flg
    },
    setTokenInfo(state,token){
      state.tokenInfo=token.token||""
      state.coinId=token.coinId||""
      state.addr=token.addr||""
      state.sendable=token.sendable||""
      state.divisible=token.divisible||""
    },
    setError(s,e){
      s.error=e
    }
  }
})
