* 寄付のお願い

2018年1月2日に暗号通貨ウォレット「もにゃ」を公開してから3年以上が経ちました。


公開して以降、たくさんの方に使っていただきましたが、暗号通貨の価格の下落、情勢の変化、他の素晴らしいウォレットアプリケーションの登場に伴い、
ユーザー数も減少し、私個人的な事情があり、メンテナンスが満足にできなくなりました。

実は、このままメンテナンスをせず、ユーザーが減るのを待ち、静かに公開を停止することを考えておりました。
しかし、2020年後半以降、暗号通貨の価格が2017年を大きく上回る水準に達し、その結果、利用者が増加してしまいました。
また、某所では3年経った今でも利用が推奨されるウォレットとなっております。

そのため、メンテナンスを継続せざるを得ない状態です。

今までサーバー等の運用を私やふじしゃん個人の資金で行っておりましたが、AWSの残高を使い切ってしまい、AWSから移行したVPSも運営会社と連絡がつかなくなってしまいました。
そのため、残高情報の取得や送金ができない状態が長く続いていました。現在は有志が建てたサーバーや公開サーバーを利用していますが、本来ならば自前のサーバーを持つべきです。

ですので、もにゃを愛用していただいている皆様にサーバー代を寄付していただきたいと考えています。

** 寄付金の用途
いただいた寄付金はサーバー使用料、その他メンテナンスにかかる費用の支払いに使います。

** お礼
寄付をしていただいた方へのお礼として、NFTをお配りしたいと考えております。
私が現在進めているNFTプロジェクトなのですが、本プロジェクトを正式公開し次第、寄付していただいたことを確認できた方に配布する予定です。
詳細は後日Twitter @MissMonacoin でお知らせします。

** 寄付方法

- MONA(ほしいMONAリスト)
  - https://monalist.komikikaku.com/list/J9D6R18kz12aM3ytRPny4DEG2qufZkekRM
- BTC
  - 1CMqfuCbAy2wN66FWvof6stRazevfMQyLv
- LTC
  - LY11FqXgc33nKybYztSPCU7qWSeTMxRG5e
- ETH、その他トークン
  - 0xE2011b4D808FD4C25C1C97F28869cC52Ee3E4994
- 日本円
  - DMください
- その他
  - 申し訳ございませんが、サーバー代として使うため、流動性がない通貨は原則ご遠慮させていただきます。

寄付を確認できた方にはNFTを差し上げたいと考えております。
