name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install deps
        run: npm ci
      - name: build site
        run: npm run build
      - name: upload web
        uses: actions/upload-artifact@v2
        with:
          name: web.apk
          path: docs/wallet
      - name: push dev
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        run: |
          git clone "git@github.com:monya-wallet/dev.git" dev
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cp -r docs/wallet/* dev
          cp -r cordovaProj/www/* dev/cwww
          cd dev
          git add .
          git commit -m "[ci skip] build on circle ci"
          git push origin master
          cd ..
      - name: push release
        if: github.ref == 'refs/heads/release'
        run: |
          git clone "git@github.com:monya-wallet/monya-wallet.github.io.git" release
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cp -r docs/wallet/* release/wallet
          cd release
          git add .
          git commit -m "[ci skip] build on circle ci"
          git push origin master
          cd ..
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"
      - name: cordova build
        run: |
          sudo npm i -g cordova@7.1.0
          wget https://services.gradle.org/distributions/gradle-4.1-bin.zip -qO gradle.zip
          sudo unzip gradle.zip -d /opt
          export PATH="$PATH:/opt/gradle-4.1/bin/"
          sudo echo $ANDROID_SDK_LICENSE_VOLUMES > $ANDROID_HOME/licenses/android-sdk-license
          sdkmanager tools "build-tools;28.0.3" "platform-tools" "platforms;android-28"
          cd cordovaProj
          npm i
          cordova platform add android
          cordova build android --release
      - name: upload apk
        uses: actions/upload-artifact@v2
        with:
          name: android-release-unsigned.apk
          path: cordovaProj/platforms/android/build/outputs/apk/android-release-unsigned.apk
